apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gdg-istanbul-event-arm64-wrong
  name: gdg-istanbul-event-arm64-wrong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdg-istanbul-event-arm64-wrong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gdg-istanbul-event-arm64-wrong
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: ghcr.io/developer-guy/gdg-istanbul-event:arm64
        name: hello-world-go
        resources: {}
status: {}
